name: codebuilddeploy-blogs

networks:
  development:
    name: codebuilddeploy
    driver: bridge

services:
  codebuilddeploy-blogs-data:
    image: codebuilddeploy.azurecr.io/codebuilddeploy-blogs-data:latest
    build:
      context: .
      dockerfile: ./src/CodeBuildDeploy.Blogs.Api/Dockerfile
      target: finalMigration
      args:
        FEED_ACCESSTOKEN: $FEED_ACCESSTOKEN
    env_file: .env
    networks:
      - development
    container_name: codebuilddeploy-blogs-data
    hostname: codebuilddeploy-blogs-data

  codebuilddeploy-blogs:
    image: codebuilddeploy.azurecr.io/codebuilddeploy-blogs:latest
    build:
      context: .
      dockerfile: ./src/CodeBuildDeploy.Blogs.Api/Dockerfile
      target: final
      args:
        FEED_ACCESSTOKEN: $FEED_ACCESSTOKEN
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5003
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CERT_PASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/code-build-deploy.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5003:5003
    networks:
      - development
    container_name: codebuilddeploy-blogs
    hostname: codebuilddeploy-blogs