name: code-build-deploy-blogs

networks:
  development:
    name: code-build-deploy
    driver: bridge

services:
  code-build-deploy-blogs:
    image: codebuilddeploy.azurecr.io/code-build-deploy-blogs:latest
    build:
      context: .
      dockerfile: ./src/CodeBuildDeploy.Blogs/Dockerfile
      target: final
      args:
        FEED_ACCESSTOKEN: $FEED_ACCESSTOKEN
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5003
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CERT_PASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/code-build-deploy.pfx
      ConnectionStrings__BlogConnection: "Server=tcp:codebuilddeploy.database.windows.net,1433;Database=codebuilddeploy;User ID=mark.pollard;Password=sqlServerAdm1n;Trusted_Connection=False;Encrypt=True;Connection Timeout=30"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5003:5003
    networks:
      - development
    container_name: code-build-deploy-blogs
    hostname: code-build-deploy-blogs