{{ $env := .Values.env.name | required "env.name is required" }}
{{ $envShort := .Values.env.shortName | required "env.shortName is required" }}
{{ $serviceName := "codebuilddeploy-blogs" }}
{{ $instanceName := printf "%s-%s" $env $serviceName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
  name: {{ $instanceName }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $env }}.codebuilddeploy.co.uk
    http:
      paths:
      - path: /api/blog
        pathType: Prefix
        backend:
          service:
            name: {{ $instanceName }}
            port:
              number: 80
      - path: /swagger/blog
        pathType: Prefix
        backend:
          service:
            name: {{ $instanceName }}
            port:
              number: 80
  - host: {{ $env }}.codebuilddeploy.com
    http:
      paths:
      - path: /api/blog
        pathType: Prefix
        backend:
          service:
            name: {{ $instanceName }}
            port:
              number: 80
      - path: /swagger/blog
        pathType: Prefix
        backend:
          service:
            name: {{ $instanceName }}
            port:
              number: 80
  tls:
    - hosts:
        - {{ $env }}.codebuilddeploy.co.uk
        - {{ $env }}.codebuilddeploy.com
      secretName: cbd-{{ $env }}-ssl-cert

status:
  loadBalancer: {}
