{{ $env := .Values.env.name | required "env.name is required" }}
{{ $envShort := .Values.env.shortName | required "env.shortName is required" }}
{{ $serviceName := "codebuilddeploy-blogs-data" }}
{{ $instanceName := printf "%s-%s" $env $serviceName }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ instanceName }}-{{ required "name populated by build" null }}
spec:
  template:
    spec:
      containers:
        - name: {{ $serviceName }}

          image: {{ required "Populated by build" null }}
          imagePullPolicy: IfNotPresent

          env:
            - name: ConnectionStrings__BlogMigrationConnection
              valueFrom:
                secretKeyRef:
                  name: cbd-{{ $env }}-secret
                  key: ConnectionStrings__BlogMigrationConnection

            - name: ASPNETCORE_ENVIRONMENT
              value: {{ $env }}

      imagePullSecrets:
        - name: cbd-pull-secret
      
      restartPolicy: "OnFailure"
